services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: quickcart-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: quickcart_products
      MYSQL_USER: quickcart
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: quickcart-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: quickcart-phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:
