[phases.setup]
nixPkgs = ['php81', 'php81Packages.composer']

[phases.install]
cmds = ['cd product-service && composer install --no-dev --optimize-autoloader']

[phases.build]
cmds = [
  'cd product-service',
  'php artisan config:cache',
  'php artisan route:cache',
  'php artisan view:cache'
]

[start]
cmd = 'cd product-service && php artisan serve --host=0.0.0.0 --port=$PORT'
