[build]
  base = "quickcart-frontend"
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://quickcart-production.up.railway.app/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
